default: &default
  adapter: postgresql
  schema_search_path: 'public,shared_extensions'
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: hotspot_development

test:
  <<: *default
  database: hotspot_test

production:
  <<: *default
  database: hotspot_production
  username: hotspot
  password: <%= ENV['HOTSPOT_DATABASE_PASSWORD'] %>
